name: GitHub Pages (Manual)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Build pages
      run: deno --allow-read --allow-write --allow-run=deno build.ts
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: output/
        if-no-files-found: error
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: output/
    - uses: actions/upload-pages-artifact@v3
      with:
        path: output/
    - uses: actions/deploy-pages@v4
      id: deployment